# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "w77q-tee"
BBFILE_PATTERN_w77q-tee = "^${LAYERDIR}/"
BBFILE_PRIORITY_w77q-tee = "8"
LAYERSERIES_COMPAT_w77q-tee = "scarthgap"

LAYERDEPENDS_w77q-tee = "core sparrow-hawk"
