# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-w77q"
BBFILE_PATTERN_meta-w77q = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-w77q = "9"
LAYERSERIES_COMPAT_meta-w77q = "scarthgap"

LAYERDEPENDS_meta-w77q = "core meta-optee-pkcs11"
